---
- name: "Mario and Tetris installation"
  become: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create docker containers
      docker_container:
        name: "super-mario"
        image: "pengbai/docker-supermario"
        state: started
        restart: "yes"
        ports: "9001:8080"
      tags: mario  

    - name: Create tetris containers
      docker_container:
        name: "tetris"
        image: "ociotec/tetris"
        state: started
        restart: "yes"
        ports: "9002:80"
      tags: tetris
...
